### ISSUE TITLE
Easy way to turn off server side JS rendering

### ISSUE THREAD

**Issue by dimroc** [olebedev/go-starter-kit#24]
I'm running into JS issues when trying to render the JS on the golang server via duktape.

Is there a line of code I can comment out or a command line I can use to toggle off server side JS rendering? I've been mucking around in here:

https://github.com/olebedev/go-starter-kit/blob/1e850a27135f90e85981c0bcc18d4df032aa1337/src/app/server/react.go#L65

I'm ultimately trying to use redux with react-router with [redux-simple-router](https://github.com/jlongster/redux-simple-router), but it doesn't render server side.

I'm merely looking for something to unblock me at this point.

**Comment by olebedev** [comment]
Easy way to discard server side JS rendering is adding your own handler instead of `app.React.Handle`. For example, it could be added [here](https://github.com/olebedev/go-starter-kit/blob/master/src/app/server/app.go#L122) as well.

It's pretty easy to write own:
```go
func noJsRender(c *echo.Context) error {
  return c.Render(http.StatusOK, "react.html", resp{
    "uuid": c.Get("uuid").(*uuid.UUID).String(),
    "title":"my awesome app",
    "meta":"my meta tags to add at the head of the page",
  })
}
```

Then replace `return app.React.Handle(c)` to `return noJsRender(c)`. That's it.

**Comment by dimroc** [comment]
Thanks Oleg
