### ISSUE TITLE
go get app/ undefined: Asset

### ISSUE THREAD

**Issue by m1halo** [olebedev/go-starter-kit#5]
Any idea why this is happening on fresh clone?
```bash
bash-3.2$ go get app
# app/server
src/app/server/app.go:64: undefined: Asset
src/app/server/app.go:65: undefined: AssetDir
src/app/server/react.go:191: undefined: Asset
```

**Comment by olebedev** [comment]
@m1halo thanks for this report!

Actually there is no any problems with `undefined: Asset`. That warning was thrown because there is no `bindata.go` file which should be created at the compile time. You just may ignore this at first time.

But, I had just found some interesting bug with javascript's dependencies. I leave this issue opened and I will fix it today, stay tuned.

**Comment by olebedev** [comment]
@m1halo now it should works, take a look https://github.com/olebedev/go-starter-kit/commit/5e7c5083b55e8e68303b15cc1aa8f89f264c4ddc

**Comment by olebedev** [comment]
It seems that it would be better to solve that instead of pick up this issue each time.

**Comment by doliver3** [comment]
It would be best to update the readme than requiring the discovery of this issue upon a fresh clone as I just did searching Google.

**Comment by olebedev** [comment]
Yup, @doliver3 you right. I'll do it right now.

**Comment by olebedev** [comment]
The problem is fixed.

**Comment by louwers** [comment]
Is it though?
```
[me@sati go-test]$ go get ./server/...
# git.extrintr.me/bart/go-test/server
server/app.go:106: undefined: Asset
server/app.go:107: undefined: AssetDir
server/app.go:108: undefined: AssetInfo
server/app.go:121: undefined: Asset
server/app.go:149: undefined: Asset
server/app.go:149: undefined: AssetDir
server/react.go:157: undefined: Asset
```
